### ISSUE TITLE
Cannot set primary on Mirror-Failover property

### ISSUE THREAD

**Issue by matanbaru** [akamai/cli-gtm#1]

**Comment by edglynes** [comment]
please review release notes. Note limited functionality supported. 
Name: 
   akamai-gtm update-property

Description: 
   Update property configuration

Usage: 
   akamai-gtm update-property [domain, property] [--datacenter] [--enable] [--disable] [--weight] [--server] [--verbose] [--json] [--complete] 

Flags: 
   --datacenter value  Apply change to specified datacenter by id or nickname.
   --enable                Enable specified datacenter(s).
   --disable               Disable specified datacenter(s).
   --weight value          Apply 'weight' to specified datacenter. (default: 0)
   --server value          Update target server for specified datacenter. Multiple server flags may be specified.
   --verbose               Display verbose result status.
   --json                  Return status in JSON format.
   --complete              Wait up to 5 minutes for change completion

domain and property are required

If enhancement is requested please note as such

**Comment by HeatfanJohn** [comment]
I created a Pull Request #3 which enables the functionality to set the primary target on a Mirror-Failover property.

**Comment by edglynes** [comment]
@HeatfanJohn @sagardeo2105 Final changes for rel 0.3.0 are in master. See the updated README for usage. I added a target arg as well as dryrun and timeout. I removed weights arg.

Pls review an try if you  have a chance. I plan to finalize and release between 7/7 and 7/16.

Thx.

**Comment by HeatfanJohn** [comment]
I get the following error on 0.3.0 on Windows when trying to test "--target":

```
C:\Users\johnma>.akamai-cli\src\cli-gtm\bin\cli-gtm.exe update-property carnival.akadns.net, funpass --target '{"datacenterId": 3131,"weight":0,"enabled":true}' --target '{"datacenterId": 3134,"weight":0,"enabled":true}'
Incorrect Usage: invalid value "'{datacenterId:" for flag -target: invalid character '\'' looking for beginning of value

Name:
   akamai-gtm update-property

Description:
   Update property configuration

```
Is this a Windows issue?

**Comment by edglynes** [comment]
on Windows, you need to use double quotes to enclose string and escape quotes in the string. The following worked or me...

C:\Users\elynes>c:\temp\akamai-gtm.exe --edgerc c:\scratch\.edgerc --section default  update-property carnival.akadns.net funpass --target "{\"datacenterId\": 3131,\"weight\":0,\"enabled\":true}" --target "{\"datacenterId\": 3134,\"weight\":0,\"enabled\":true}"
[31mProperty not found[0m

**Comment by HeatfanJohn** [comment]
Thanks, @edglynes Please do me a favor and edit the domain name in your comment to xxxxxx.akadns.net ... just to be safe ... I updated my comment.

**Comment by sagardeo2105** [comment]
I will give it a try today @edglynes. 
Thanks for pushing this out :)

**Comment by sagardeo2105** [comment]
Hi @edglynes I tested it out and works fine :) 
The --dry-run flag does not seem to be working though. Even If I use --dry-run, it goes ahead and updates the property.

Another thing I would have suggest is to add propertyName to the target json object. 
This way it will allow us to run it for multiple properties under 1 domain to be routed to the required datacenter and weight.

**Comment by edglynes** [comment]
@sagardeo2105 Thx for testing. How did you ascertain that --dryrun didn't work? If you specify --dryrun, the command outputs the proposed changes to the console but does NOT update the backend.

The --target attribute reflects the target object content in properties. It would not be propriate to add additional fields. The update-datacenter command updates a the associated target references in ALL properties. Can you more clearly state the use case you are trying to address? Thx.

**Comment by sagardeo2105** [comment]
@edglynes When I used --dryrun, it did not actually output the proposed changes but rather went ahead and made the change in the GTM property. I could see the property getting updated after running the command.

Ignore the part of propertyName request. It might not be most efficient.

**Comment by edglynes** [comment]
@sagardeo2105  pls provide the command line you used with --dryrun. obfuscate any info that is proprietary. thx.

**Comment by sagardeo2105** [comment]
./akamai-gtm --section ccu --edgerc ~/.edgerc update-property abc.ca.akadns.net test --dry-run -target '{"datacenterId": 3135,"weight":1,"enabled":true}' -target '{"datacenterId": 3136,"weight":1,"enabled":true}'

**Comment by edglynes** [comment]
ok, so dryrun is one word, eg --dryrun. The application ignored --dry-run because it doesn't recognize it.

**Comment by sagardeo2105** [comment]
Ahh Crap! Thanks :) I will test it out

**Comment by sagardeo2105** [comment]
@edglynes When is this planned to be released? Any estimated date for this?

**Comment by edglynes** [comment]
By July end. Have some current work to juggle and internal process to follow. I'll comment when available.

**Comment by edglynes** [comment]
@sagardeo2105 @HeatfanJohn Release is published, https://github.com/akamai/cli-gtm/releases/tag/0.3.0

**Comment by sagardeo2105** [comment]
Thanks a lot @edglynes :)
